<a href="https://colab.research.google.com/github/priyansh4320/Pytorch_practice/blob/main/pytorch1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.0.1+cu118'

# tensor

In [3]:
#type1
#scaler
scaler = torch.tensor(4)
scaler

tensor(4)

In [4]:
scaler.ndim

0

In [5]:
# get tensor back to int
scaler.item()

4

In [6]:
#type2
#vector
vector = torch.tensor([1,2,3,4])
vector


tensor([1, 2, 3, 4])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([4])

In [9]:
#type 3
#matrix
matrix = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
matrix

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([3, 3])

In [12]:
#type 4
#tensor
tensor = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])