<a href="https://colab.research.google.com/github/priyansh4320/Pytorch_practice/blob/main/pytorch4_matrix_multiplication_and_aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'2.0.1+cu118'

# tensor

In [ ]:
#type1
#scaler
scaler = torch.tensor(4)
scaler

tensor(4)

In [ ]:
scaler.ndim

0

In [ ]:
# get tensor back to int
scaler.item()

4

In [ ]:
#type2
#vector
vector = torch.tensor([1,2,3,4])
vector


tensor([1, 2, 3, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([4])

In [ ]:
#type 3
#matrix
matrix = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
matrix

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
#type 4
#tensor
tensor = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors
random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.



``
start with random mo.--> look at data--> update random no--> look at data-->update random no.
``



In [ ]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5913, 0.5086, 0.1337, 0.8002],
        [0.9361, 0.3679, 0.3383, 0.1587],
        [0.0965, 0.3438, 0.1352, 0.3310]])

In [ ]:
# create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3,256,256)) # height=256 , width=256, color channels=3
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 256, 256]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.2824, 0.2745, 0.6158,  ..., 0.6479, 0.2988, 0.8560],
         [0.4281, 0.2199, 0.7767,  ..., 0.2755, 0.0052, 0.2118],
         [0.3612, 0.1992, 0.4433,  ..., 0.0954, 0.9924, 0.6944],
         ...,
         [0.7862, 0.7713, 0.3650,  ..., 0.2182, 0.4303, 0.9526],
         [0.9229, 0.9599, 0.9974,  ..., 0.0299, 0.2984, 0.6251],
         [0.1856, 0.0349, 0.6207,  ..., 0.2957, 0.5707, 0.1681]],

        [[0.9258, 0.5036, 0.8306,  ..., 0.3870, 0.2532, 0.7350],
         [0.7536, 0.2946, 0.7431,  ..., 0.0420, 0.4212, 0.1326],
         [0.5378, 0.0407, 0.1316,  ..., 0.0905, 0.2531, 0.9329],
         ...,
         [0.1199, 0.5617, 0.5909,  ..., 0.0167, 0.6343, 0.2092],
         [0.8313, 0.6360, 0.3820,  ..., 0.1947, 0.0649, 0.5602],
         [0.4853, 0.4424, 0.9178,  ..., 0.8765, 0.0889, 0.9085]],

        [[0.8646, 0.5384, 0.3831,  ..., 0.2100, 0.8470, 0.9707],
         [0.4488, 0.4819, 0.9149,  ..., 0.3170, 0.5615, 0.8888],
         [0.9000, 0.5103, 0.2313,  ..., 0.7610, 0.1317, 0.

### Zero tensor
a tensor containing all zeros

In [ ]:
zero_tensor = torch.zeros(size=(1,4,3))
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

### Range Tensor
tensor with a range

In [ ]:
range_tensor = torch.arange(1,10)
range_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range_tensor = torch.arange(start=1,end=100,step=25) #step : gap in range 1+25 ,25+25 etc
range_tensor

tensor([ 1, 26, 51, 76])

In [ ]:
# Reshape as 2x2 or matrix tensor
range_tensor.reshape(2,2)

tensor([[ 1, 26],
        [51, 76]])

# Tensor Datatypes

**Note:** tensor datatypes is reason for one of the 3 big errors you'll run into with pytorch.
1. tensor not right datatype
2. tensor not right shape
3. tensor not on right device

In [ ]:
#float32 tensor
float32_tensor = torch.tensor([1.,2.,3.,4.],dtype=None)
float32_tensor

tensor([1., 2., 3., 4.])

In [ ]:
float32_tensor.dtype #default tensor type is float32

torch.float32

In [ ]:
#three main parameter for tensor datatype
float32_tensor = torch.tensor([1.,2.,3.,4.],
                              dtype = None,   # what datatype is tensor(e.g float32 or float16)
                              device= None,   # what device is your tensor on
                              requires_grad=False) # whether or not to track gradlines
float32_tensor

tensor([1., 2., 3., 4.])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
# change datatype of tensor
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([1., 2., 3., 4.], dtype=torch.float16)

In [ ]:
float16_tensor * float32_tensor

tensor([ 1.,  4.,  9., 16.])

### Check details of tensor
1. tensor not right datatype- use `tensor.dtype ` to check datatype
2. tensor not right shape - use `tensor.shape` to check shape
3. tensor not on right device - use `tensor.device` to check which device is tensor on.

In [ ]:
random_tensor = torch.rand(size=(3,3))
print("datatype: ",random_tensor.dtype)
print("shape: ",random_tensor.shape)
print("device: ",random_tensor.device)


datatype:  torch.float32
shape:  torch.Size([3, 3])
device:  cpu


# tensor manipulation
 it includes set of operations:
 1. add
 2. subt
 3. multipy(element-wise)
 4. divide
 5. matrix mutiplication

In [3]:
# add
some_tensor = torch.tensor([1,2,3,4])
some_tensor + 10

tensor([11, 12, 13, 14])

In [4]:
#subt
some_tensor - 10

tensor([-9, -8, -7, -6])

In [5]:
# mutiply (element-wise)
some_tensor * 10

tensor([10, 20, 30, 40])

In [6]:
#divide
some_tensor / 10

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [8]:
#useing inbuilt function
print(torch.add(some_tensor,10))  #add method
print(torch.sub(some_tensor,10))  #subt method
print(torch.mul(some_tensor,10))  # multiply method
print(torch.div(some_tensor,10))  #division method

tensor([11, 12, 13, 14])
tensor([-9, -8, -7, -6])
tensor([10, 20, 30, 40])
tensor([0.1000, 0.2000, 0.3000, 0.4000])


### matrix multiplication
two ways to multiply matrix:
1. element-wise
2. dot product

two basic rules of matrix multiplication (dot product):
1. inner dimension must match
- (3,2) * (3,2) : 'won't work'
- (2,**3**) * (**3**,2) : 'will work'

2. result matrix has shape of outer dimension
- (2,3) * (3,2) --> (2,2)
- (3,2) * (2,3) --> (3,3)

In [9]:
# matmul method (use dot product method)
some_tensor = torch.tensor([1,2,3])
torch.matmul(some_tensor, some_tensor)

tensor(14)

In [11]:
#manual dot product
# [1,2,3] matmul [1,2,3]
# =
1*1 + 2*2 + 3*3

14

In [10]:
# element-wise
some_tensor * some_tensor

tensor([1, 4, 9])

### common error : shape error
let's reproduce the error

In [13]:
tensor_A = torch.rand(3,2)
tensor_B = torch. rand(3,2)
torch.matmul(tensor_A,tensor_B)

RuntimeError: ignored

### transpose
- this method can be used to get rid of this error
- it shift the dimension of the matrix

In [14]:
# tensor.T is is used to transpose a tensor
torch.matmul(tensor_A,tensor_B.T)  # we transposed tensor_B using .T

tensor([[0.1818, 0.6293, 0.4455],
        [0.0501, 0.5176, 0.3002],
        [0.2803, 0.2949, 0.3389]])

In [16]:
# let's look at the shape
print("original: ",tensor_A.shape, tensor_B.shape)
print("After Transpose B: ",tensor_A.shape, tensor_B.T.shape) #inner dim must match

original:  torch.Size([3, 2]) torch.Size([3, 2])
After Transpose B:  torch.Size([3, 2]) torch.Size([2, 3])


# Tensor aggregation
1. min
2. max
3. mean
4. sum

In [18]:
tensor_A = torch.arange(0,100,10)
tensor_A

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
# two ways to aggreagate
# min
torch.min(tensor_A)  ,  tensor_A.min()

(tensor(0), tensor(0))

In [20]:
#max
torch.max(tensor_A) ,   tensor_A.max()

(tensor(90), tensor(90))

### common error: datatype not correct
let's produce the ERROR

In [21]:
#MEAN
torch.mean(tensor_A) # here we get error because tensor is of type int64 == Long

RuntimeError: ignored

In [22]:
#mean : require float32 type tensor default
# change to type of tensor to float32
torch.mean(tensor_A.type(torch.float32))  , tensor_A.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [23]:
#sum
torch.sum(tensor_A)  ,  tensor_A.sum()

(tensor(450), tensor(450))