<a href="https://colab.research.google.com/github/priyansh4320/Pytorch_practice/blob/main/pytorch2_random_and_zero_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.0.1+cu118'

# tensor

In [ ]:
#type1
#scaler
scaler = torch.tensor(4)
scaler

tensor(4)

In [ ]:
scaler.ndim

0

In [ ]:
# get tensor back to int
scaler.item()

4

In [ ]:
#type2
#vector
vector = torch.tensor([1,2,3,4])
vector


tensor([1, 2, 3, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([4])

In [ ]:
#type 3
#matrix
matrix = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
matrix

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
#type 4
#tensor
tensor = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors
random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.



``
start with random mo.--> look at data--> update random no--> look at data-->update random no.
``



In [ ]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5913, 0.5086, 0.1337, 0.8002],
        [0.9361, 0.3679, 0.3383, 0.1587],
        [0.0965, 0.3438, 0.1352, 0.3310]])

In [ ]:
# create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3,256,256)) # height=256 , width=256, color channels=3
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 256, 256]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.2824, 0.2745, 0.6158,  ..., 0.6479, 0.2988, 0.8560],
         [0.4281, 0.2199, 0.7767,  ..., 0.2755, 0.0052, 0.2118],
         [0.3612, 0.1992, 0.4433,  ..., 0.0954, 0.9924, 0.6944],
         ...,
         [0.7862, 0.7713, 0.3650,  ..., 0.2182, 0.4303, 0.9526],
         [0.9229, 0.9599, 0.9974,  ..., 0.0299, 0.2984, 0.6251],
         [0.1856, 0.0349, 0.6207,  ..., 0.2957, 0.5707, 0.1681]],

        [[0.9258, 0.5036, 0.8306,  ..., 0.3870, 0.2532, 0.7350],
         [0.7536, 0.2946, 0.7431,  ..., 0.0420, 0.4212, 0.1326],
         [0.5378, 0.0407, 0.1316,  ..., 0.0905, 0.2531, 0.9329],
         ...,
         [0.1199, 0.5617, 0.5909,  ..., 0.0167, 0.6343, 0.2092],
         [0.8313, 0.6360, 0.3820,  ..., 0.1947, 0.0649, 0.5602],
         [0.4853, 0.4424, 0.9178,  ..., 0.8765, 0.0889, 0.9085]],

        [[0.8646, 0.5384, 0.3831,  ..., 0.2100, 0.8470, 0.9707],
         [0.4488, 0.4819, 0.9149,  ..., 0.3170, 0.5615, 0.8888],
         [0.9000, 0.5103, 0.2313,  ..., 0.7610, 0.1317, 0.

# Zero tensor
a tensor containing all zeros

In [5]:
zero_tensor = torch.zeros(size=(1,4,3))
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

# Range Tensor
tensor with a range

In [6]:
range_tensor = torch.arange(1,10)
range_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
range_tensor = torch.arange(start=1,end=100,step=25) #step : gap in range 1+25 ,25+25 etc
range_tensor

tensor([ 1, 26, 51, 76])

In [14]:
# Reshape as 2x2 or matrix tensor
range_tensor.reshape(2,2)

tensor([[ 1, 26],
        [51, 76]])